language:  cpp

matrix:
  include:
    - os:        osx
      osx_image: xcode9.3
      env:
        - TARGET=mac TEST=test

    - os:        osx
      osx_image: xcode7.3
      env:
        - TARGET=mac TEST=test

    - os:        linux
      dist:      xenial
      env:
        - TARGET=linux TEST=test

    - os:        linux
      services:
        - docker
      before_install:
        - docker run -d --name cosmic -v $(pwd):/libsfz -w /libsfz ubuntu:cosmic sleep infinity
        - docker ps
      install:
        - $SH apt-get update
        - $SH apt-get install -y --no-install-recommends build-essential clang make python
      env:
        - TARGET=linux TEST=test SH="docker exec cosmic"

    - os:        linux
      services:
        - docker
      before_install:
        - docker run -d --name cosmic -v $(pwd):/libsfz -w /libsfz ubuntu:cosmic sleep infinity
        - docker ps
      install:
        - $SH apt-get update
        - $SH apt-get install -y --no-install-recommends build-essential clang make python
        - $SH apt-get install -y --no-install-recommends mingw-w64 xvfb wine
      env:
        - TARGET=win TEST=test-wine SH="docker exec cosmic"

script:
  - $SH ./configure -o $TARGET
  - $SH make
  - $SH make $TEST
