name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python3 python3-pip build-essential clang make
          pip3 install --user pytest pygments
      - name: ./configure
        run: ./configure
      - name: make
        run: make
      - name: make test
        run: make test

  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install deps
        run: |
          brew update
          brew install ninja sfiera/gn/gn
          pip3 install --user pytest pygments
      - name: ./configure
        run: ./configure
      - name: make
        run: make
      - name: make test
        run: make test
